
function OAS_TranslatePos(pos,identifier)
{pos=pos.toLowerCase();var position='';switch(identifier)
{default:if(pos=='rec1')
{width='336';height='280';position='rec1';site='ibd.homepage/newhome_halfpageads';section='';displaySponsorshipText=false;}else
if(pos=='tc1')
{width='120';height='60';position='tc1';site='ibd.tradingcenter';section='';displaySponsorshipText=false;}else
if(pos=='tc2')
{width='120';height='60';position='tc2';site='ibd.tradingcenter';section='';displaySponsorshipText=false;}else
if(pos=='tc3')
{width='120';height='60';position='tc3';site='ibd.tradingcenter';section='';displaySponsorshipText=false;}else
if(pos=='tc4')
{width='120';height='60';position='tc4';site='ibd.tradingcenter';section='';displaySponsorshipText=false;}else
if(pos=='tc5')
{width='120';height='60';position='tc5';site='ibd.tradingcenter';section='';displaySponsorshipText=false;}else
if(pos=='tc6')
{width='120';height='60';position='tc6';site='ibd.tradingcenter';section='';displaySponsorshipText=false;}else
if(pos=='toolsmodbtn1')
{width='130';height='30';position='toolsmodbtn1';site='ibd.researchtoolsmod';section='marketdirection';displaySponsorshipText=false;}else
if(pos=='toolsmodbtn2')
{width='130';height='30';position='toolsmodbtn2';site='ibd.researchtoolsmod';section='findstocks';displaySponsorshipText=false;}else
if(pos=='toolsmodbtn3')
{width='130';height='30';position='toolsmodbtn3';site='ibd.researchtoolsmod';section='evaluatestocks';displaySponsorshipText=false;}else
if(pos=='toolsmodbtn4')
{width='130';height='30';position='toolsmodbtn4';site='ibd.researchtoolsmod';section='trackstocks';displaySponsorshipText=false;}else
if(pos=='rec2')
{width='336';height='280';position='rec2';site='ibd.homepage/homepage';section='';displaySponsorshipText=false;}else
if(pos=='rec3')
{width='336';height='62';position='rec3';site='ibd.homepage/homepage';section='';displaySponsorshipText=false;}else
if(pos=='tc7')
{width='120';height='60';position='tc7';site='ibd.tradingcenter';section='';displaySponsorshipText=false;}else
if(pos=='tc8')
{width='120';height='60';position='tc8';site='ibd.tradingcenter';section='';displaySponsorshipText=false;}else
if(pos=='housetop')
{width='336';height='130';position='housetop';site='ibd.homepage/homepage';section='';displaySponsorshipText=false;}else
if(pos=='intropage')
{width='760';height='600';position='intropage';site='ibd.intropage';section='';displaySponsorshipText=false;}else
if(pos=='masthead')
{width='88';height='31';position='masthead';site='ibd.homepage/homepage';section='';displaySponsorshipText=true;}else
if(pos=='popularmodbtn')
{width='130';height='30';position='popularmodbtn';site='ibd.mostpopular';section='';displaySponsorshipText=false;}else
if(pos=='house2')
{width='336';height='130';position='house2';site='ibd.ros';section='';displaySponsorshipText=false;}else
if(pos=='topratedbtn')
{width='130';height='30';position='topratedbtn';site='ibd.homepage/homepage';section='';displaySponsorshipText=false;}
break;}
if(position.length>0)
{position='pos='+position+';';}
if(section.length>0)
{section='sect='+section+';';}
return position;}
